# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Modified_Hans_Gibbs <- function(X, y, beta_init, a1 = 1, b1 = 1, u1 = 1, v1 = 1, nsamples = 100L, lambda_init = 0.5, sigma2_init = 1, thin = 1L, verbose = 100L, tune_lambda2 = TRUE, rao_blackwellization = FALSE) {
    .Call(`_BayesianLasso_Modified_Hans_Gibbs`, X, y, beta_init, a1, b1, u1, v1, nsamples, lambda_init, sigma2_init, thin, verbose, tune_lambda2, rao_blackwellization)
}

Modified_PC_Gibbs <- function(X, y, a1 = 1, b1 = 1, u1 = 1, v1 = 1, nsamples = 100L, lambda_init = 1, sigma2_init = 1, thin = 1L, verbose = 100L) {
    .Call(`_BayesianLasso_Modified_PC_Gibbs`, X, y, a1, b1, u1, v1, nsamples, lambda_init, sigma2_init, thin, verbose)
}

MillsRatio <- function(d) {
    .Call(`_BayesianLasso_MillsRatio`, d)
}

zlasso <- function(a, b, c, logarithm) {
    .Call(`_BayesianLasso_zlasso`, a, b, c, logarithm)
}

dlasso <- function(x, a, b, c, logarithm) {
    .Call(`_BayesianLasso_dlasso`, x, a, b, c, logarithm)
}

plasso <- function(q, a, b, c) {
    .Call(`_BayesianLasso_plasso`, q, a, b, c)
}

qlasso <- function(p, a, b, c) {
    .Call(`_BayesianLasso_qlasso`, p, a, b, c)
}

rlasso <- function(n, a, b, c) {
    .Call(`_BayesianLasso_rlasso`, n, a, b, c)
}

elasso <- function(a, b, c) {
    .Call(`_BayesianLasso_elasso`, a, b, c)
}

vlasso <- function(a, b, c) {
    .Call(`_BayesianLasso_vlasso`, a, b, c)
}

mlasso <- function(a, b, c) {
    .Call(`_BayesianLasso_mlasso`, a, b, c)
}

