# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesian_lasso_gibbs_c <- function(mX, vy, lambda, sigma2_hat, a, b, u, v, nsamples, verbose) {
    .Call(`_BayesianLasso_bayesian_lasso_gibbs_c`, mX, vy, lambda, sigma2_hat, a, b, u, v, nsamples, verbose)
}

Modified_PC_Gibbs <- function(mX, vy, a1, b1, u1, v1, nsamples, lambda_init, sigma2_init, verbose) {
    .Call(`_BayesianLasso_Modified_PC_Gibbs`, mX, vy, a1, b1, u1, v1, nsamples, lambda_init, sigma2_init, verbose)
}

bayesian_lasso_gibbs_tune_pgtn_c <- function(mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, trunc) {
    .Call(`_BayesianLasso_bayesian_lasso_gibbs_tune_pgtn_c`, mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, trunc)
}

bayesian_lasso_gibbs_default_c <- function(mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, inv_gauss_type) {
    .Call(`_BayesianLasso_bayesian_lasso_gibbs_default_c`, mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, inv_gauss_type)
}

bayesian_lasso_gibbs_approx_c <- function(mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, inv_gauss_type, trunc) {
    .Call(`_BayesianLasso_bayesian_lasso_gibbs_approx_c`, mX, vy, vbeta_init, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose, inv_gauss_type, trunc)
}

expit_c <- function(x) {
    .Call(`_BayesianLasso_expit_c`, x)
}

sq_inv_mills_7sf <- function(x) {
    .Call(`_BayesianLasso_sq_inv_mills_7sf`, x)
}

right_mills_7sf <- function(x) {
    .Call(`_BayesianLasso_right_mills_7sf`, x)
}

right_mills_12sf <- function(x) {
    .Call(`_BayesianLasso_right_mills_12sf`, x)
}

MillsRatio <- function(x) {
    .Call(`_BayesianLasso_MillsRatio`, x)
}

zcalc_7sf <- function(a, b, c, type) {
    .Call(`_BayesianLasso_zcalc_7sf`, a, b, c, type)
}

calculate_lasso_dist_stats_c_v1 <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_calculate_lasso_dist_stats_c_v1`, a_val, b_val, c_val)
}

calculate_lasso_dist_stats_c_v2 <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_calculate_lasso_dist_stats_c_v2`, a_val, b_val, c_val)
}

logSumExp_c <- function(vx) {
    .Call(`_BayesianLasso_logSumExp_c`, vx)
}

zlasso_c_v1 <- function(a_val, b_val, c_val, logarithm) {
    .Call(`_BayesianLasso_zlasso_c_v1`, a_val, b_val, c_val, logarithm)
}

zlasso <- function(a_val, b_val, c_val, logarithm) {
    .Call(`_BayesianLasso_zlasso`, a_val, b_val, c_val, logarithm)
}

dlasso_c_v1 <- function(vx, a_val, b_val, c_val, logarithm) {
    .Call(`_BayesianLasso_dlasso_c_v1`, vx, a_val, b_val, c_val, logarithm)
}

dlasso <- function(vx, a_val, b_val, c_val, logarithm) {
    .Call(`_BayesianLasso_dlasso`, vx, a_val, b_val, c_val, logarithm)
}

plasso_c_v1 <- function(vx, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_plasso_c_v1`, vx, a_val, b_val, c_val)
}

plasso <- function(vx, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_plasso`, vx, a_val, b_val, c_val)
}

qlasso_fast_c_v1 <- function(u, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_qlasso_fast_c_v1`, u, a_val, b_val, c_val)
}

qlasso <- function(u, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_qlasso`, u, a_val, b_val, c_val)
}

rlasso_fast_c_v1 <- function(n, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_rlasso_fast_c_v1`, n, a_val, b_val, c_val)
}

rlasso <- function(n, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_rlasso`, n, a_val, b_val, c_val)
}

elasso_c_v1 <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_elasso_c_v1`, a_val, b_val, c_val)
}

elasso <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_elasso`, a_val, b_val, c_val)
}

vlasso_c_v1 <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_vlasso_c_v1`, a_val, b_val, c_val)
}

vlasso <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_vlasso`, a_val, b_val, c_val)
}

mlasso <- function(a_val, b_val, c_val) {
    .Call(`_BayesianLasso_mlasso`, a_val, b_val, c_val)
}

lasso_gibbs_Bc <- function(mX, vy, a, b, u, v, nsamples, vbeta_init, lambda_init, sigma2_init, verbose) {
    .Call(`_BayesianLasso_lasso_gibbs_Bc`, mX, vy, a, b, u, v, nsamples, vbeta_init, lambda_init, sigma2_init, verbose)
}

Modified_Hans_Gibbs <- function(mX, vy, a1, b1, u1, v1, nsamples, beta_init, lambda_init, sigma2_init, verbose) {
    .Call(`_BayesianLasso_Modified_Hans_Gibbs`, mX, vy, a1, b1, u1, v1, nsamples, beta_init, lambda_init, sigma2_init, verbose)
}

rrinvgauss <- function(vmu, vlambda) {
    .Call(`_BayesianLasso_rrinvgauss`, vmu, vlambda)
}

rinvgaussian_c <- function(vmu, vlambda) {
    .Call(`_BayesianLasso_rinvgaussian_c`, vmu, vlambda)
}

rinvgaussian_slice <- function(x, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_rinvgaussian_slice`, x, a_val, b_val, c_val)
}

rinvgaussian_slice_c <- function(vx, vmu, vlambda) {
    .Call(`_BayesianLasso_rinvgaussian_slice_c`, vx, vmu, vlambda)
}

slice_sampler_precision_c <- function(x, a_val, b_val, c_val) {
    .Call(`_BayesianLasso_slice_sampler_precision_c`, x, a_val, b_val, c_val)
}

zetaOneLentz_c <- function(x, tol, maxiter) {
    .Call(`_BayesianLasso_zetaOneLentz_c`, x, tol, maxiter)
}

zetaOne_c <- function(x) {
    .Call(`_BayesianLasso_zetaOne_c`, x)
}

zeta_c <- function(k, x) {
    .Call(`_BayesianLasso_zeta_c`, k, x)
}

